### ISSUE TITLE
Thread-safeness of PGP class' method

### ISSUE THREAD

**Issue by hestati63** [KAIST-IS521/2018s-onion-team4#11]
`Encrypt` and `Decrypt` methods should be thread-safe.

Can you check it?

It not, change them to thread-safe.

**Comment by khsdo95** [comment]
In Manual,

2.8 Multi Threading
The GPGME library is not entirely thread-safe, but it can still be used in a multi-threaded environment if some care is taken. If the following requirements are met, there should be no race conditions to worry about:

GPGME supports the thread libraries pthread and GNU Pth. The support for this has to be enabled at compile time. GPGME will automatically detect the location in which the thread libraries are installed and activate the support for them at build time.
Support for other thread libraries is very easy to add. Please contact us if you have the need.

1. If you want to use GPGME with threads, you must link to the right version of the library. The name of the right library is libgpgme- followed by the name of the thread package you use. For example, if you use GNU Pth, the right name is libgpgme-pth. Use the Automake macros or gpgme-config program for simplicity.

2. The function gpgme_check_version must be called before any other function in the library, because it initializes the thread support subsystem in GPGME. To achieve this in multi-threaded programs, you must synchronize the memory with respect to other threads that also want to use GPGME. For this, it is sufficient to call gpgme_check_version before creating the other threads using GPGME1.

3. Any gpgme_data_t and gpgme_ctx_t object must only be accessed by one thread at a time. If multiple threads want to deal with the same object, the caller has to make sure that operations on that object are fully synchronized.

4. Only one thread at any time is allowed to call gpgme_wait. If multiple threads call this function, the caller must make sure that all invocations are fully synchronized. It is safe to start asynchronous operations while a thread is running in gpgme_wait.

5. The function gpgme_strerror is not thread safe. You have to use gpgme_strerror_r instead.

I think all conditions can be satisfied in our project, except for 3.
We used one global context, so It should be synchronized.
Otherwise, we need to create new context whenever decrypt or encrypt
It can make condition 3 satisfied.

**Comment by hestati63** [comment]
This is one of most urgent work on building Onion Messenger.

**Comment by khsdo95** [comment]
I make a commit. It makes ctx disposable.
10e29e0813470ab0e36833c3813f8732cc70e2f7
